# Generated by Django 6.0.7 on 2026-08-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
